# Generated by Django 5.2.14 on 2026-05-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения (используется если файл не загружен)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения (используется если файл не загружен)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Фото в галерее',
                'verbose_name_plural': 'Галерея',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Kruassanov', max_length=120, verbose_name='Название компании')),
                ('tagline', models.CharField(blank=True, default='Maison de pâtisserie', max_length=200, verbose_name='Подзаголовок шапки')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Логотип')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/kruassanov.tm/', verbose_name='Instagram')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=150, verbose_name='Часы работы')),
                ('hero_title', models.CharField(default="L'art de la pâtisserie", max_length=200, verbose_name='Hero — заголовок')),
                ('hero_subtitle', models.CharField(default='Французская кондитерская — каждый десерт создан вручную с любовью.', max_length=300, verbose_name='Hero — подзаголовок')),
                ('hero_button_text', models.CharField(default='Смотреть меню', max_length=60, verbose_name='Hero — текст кнопки')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Hero — фоновое изображение')),
                ('hero_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=2000&q=80', verbose_name='Hero — URL изображения (если не загружено)')),
                ('about_title', models.CharField(default='Искусство, рождённое во Франции', max_length=200, verbose_name='О компании — заголовок')),
                ('about_text', models.TextField(default='Kruassanov — это маленькая мастерская, где каждый день рождаются десерты по лучшим традициям французской кондитерской школы. Свежие ингредиенты, ручная работа и безупречный вкус.', verbose_name='О компании — короткий текст')),
                ('about_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=1600&q=80', verbose_name='О компании — изображение URL')),
                ('footer_text', models.CharField(default='© Kruassanov.tm — Maison de pâtisserie', max_length=300, verbose_name='Текст подвала')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='TMT', max_length=8, verbose_name='Валюта')),
                ('weight', models.CharField(blank=True, help_text='Например: 80 г, 6 шт.', max_length=50, verbose_name='Вес / порция')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения (используется если файл не загружен)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
