# Generated by Django 5.2.14 on 2026-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, help_text='Локальный путь в static/, например images/category.jpg', max_length=255, verbose_name='Путь к изображению (если файл не загружен)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_url',
            field=models.CharField(blank=True, help_text='Локальный путь в static/, например images/gallery.jpg', max_length=255, verbose_name='Путь к изображению (если файл не загружен)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, help_text='Локальный путь в static/, например images/product.jpg', max_length=255, verbose_name='Путь к изображению (если файл не загружен)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_image_url',
            field=models.CharField(blank=True, default='images/1517433670267-08bbd4be890f.jpg', help_text='Локальный путь в static/, например images/about.jpg', max_length=255, verbose_name='О компании — путь к изображению'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_url',
            field=models.CharField(blank=True, default='images/1555507036-ab1f4038808a.jpg', help_text='Локальный путь в static/, например images/hero.jpg', max_length=255, verbose_name='Hero — путь к изображению (если не загружено)'),
        ),
    ]
